# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11.3-browsers
general:
  branches:
    only:
      - develop # list of branches to build
      - release-us
      - release-uk
      - release-eu
      - release-ca
jobs:
  build:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-bootstrapped
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # NPM Install & Overwrite the slate build-js file with our custom one that compiles ES6 / React
      - run: npm run bootstrap
      # Save the cached setup
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-bootstrapped
      # Persist the specified paths (workspace/echo-output) into the workspace for use in deploy job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a  
          # directory on the container which is taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - .
  deploy_develop:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
        #Install slate to use slate deploy commands (v0.14)
      - run: sudo npm i -g @shopify/slate
      - run:
          name: Generate dev env setting
          command: | #Change theme ID for each level 
            echo '
            development:
              password:' $SLATE_PASSWORD_DEV '
              theme_id: "live"
              store: muckboot-dev.myshopify.com
              ignore_files:
                - theme.shogun.landing.liquid
                - page.shogun.default.liquid 
                - page.shogun.landing.liquid
                - product.shogun.custom.liquid
                - shogun-head.liquid
                - shogun-products.liquid 
                # - settings_data.json #Commented out to keep dev sync with repo changes' > ./config.yml
      - run:
          name: Deploy
          command: npm run deploy
  deploy_release_us:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
        #Install slate to use slate deploy commands (v0.14)
      - run: sudo npm i -g @shopify/slate
      - run:
          name: Generate prod env setting
          command: | #Change theme ID for each level
            echo '
            production:
              password:' $SLATE_PASSWORD_PROD_US '
              theme_id: "live"
              store: muckboot-usa.myshopify.com
              ignore_files:
                - theme.shogun.landing.liquid
                - page.shogun.default.liquid 
                - page.shogun.landing.liquid
                - product.shogun.custom.liquid
                - shogun-head.liquid
                - shogun-products.liquid 
                - settings_data.json' > ./config.yml
      - run:
          name: Deploy
          command: slate deploy -e production

  deploy_release_uk:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
        #Install slate to use slate deploy commands (v0.14)
      - run: sudo npm i -g @shopify/slate
      - run:
          name: Generate prod env setting
          command: | #Change theme ID for each level
            echo '
            production:
              password:' $SLATE_PASSWORD_PROD_UK '
              theme_id: "live"
              store: muckboot-uk.myshopify.com
              ignore_files:
                - settings_data.json' > ./config.yml
      - run:
          name: Deploy
          command: slate deploy -e production

  deploy_release_eu:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
        #Install slate to use slate deploy commands (v0.14)
      - run: sudo npm i -g @shopify/slate
      - run:
          name: Generate prod env setting
          command: | #Change theme ID for each level
            echo '
            production:
              password:' $SLATE_PASSWORD_PROD_EU '
              theme_id: "live"
              store: muckboot-eu.myshopify.com
              ignore_files:
                - settings_data.json' > ./config.yml
      - run:
          name: Deploy
          command: slate deploy -e production
  deploy_release_ca:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo

        #Install slate to use slate deploy commands (v0.14)
      - run: sudo npm i -g @shopify/slate
      - run:
          name: Generate prod env setting
          command: | #Change theme ID for each level
            echo '
            production:
              password:' $SLATE_PASSWORD_PROD_CA '
              theme_id: "live"
              store: muckboot-ca.myshopify.com
              ignore_files:
                - settings_data.json' > ./config.yml
      - run:
          name: Deploy
          command: slate deploy -e production
workflows:
  version: 2
  build_deploy_dev:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

  build_deploy_release_us:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release-us
      - deploy_release_us:
          requires:
            - build
          filters:
            branches:
              only:
                - release-us

  build_deploy_release_uk:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release-uk
      - deploy_release_uk:
          requires:
            - build
          filters:
            branches:
              only:
                - release-uk

  build_deploy_release_eu:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release-eu
      - deploy_release_eu:
          requires:
            - build
          filters:
            branches:
              only:
                - release-eu

  build_deploy_release_ca:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release-ca
      - deploy_release_ca:
          requires:
            - build
          filters:
            branches:
              only:
                - release-ca